// Generated by gencpp from file robot/direction_msg.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_DIRECTION_MSG_H
#define ROBOT_MESSAGE_DIRECTION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct direction_msg_
{
  typedef direction_msg_<ContainerAllocator> Type;

  direction_msg_()
    : speed(0)
    , reverse(0)
    , turn(0)  {
    }
  direction_msg_(const ContainerAllocator& _alloc)
    : speed(0)
    , reverse(0)
    , turn(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _reverse_type;
  _reverse_type reverse;

   typedef int32_t _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::robot::direction_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::direction_msg_<ContainerAllocator> const> ConstPtr;

}; // struct direction_msg_

typedef ::robot::direction_msg_<std::allocator<void> > direction_msg;

typedef boost::shared_ptr< ::robot::direction_msg > direction_msgPtr;
typedef boost::shared_ptr< ::robot::direction_msg const> direction_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::direction_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::direction_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::direction_msg_<ContainerAllocator1> & lhs, const ::robot::direction_msg_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.reverse == rhs.reverse &&
    lhs.turn == rhs.turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::direction_msg_<ContainerAllocator1> & lhs, const ::robot::direction_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::direction_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::direction_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::direction_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::direction_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::direction_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::direction_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8072a12186ad0921bcc9ce37f809e20";
  }

  static const char* value(const ::robot::direction_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8072a12186ad092ULL;
  static const uint64_t static_value2 = 0x1bcc9ce37f809e20ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/direction_msg";
  }

  static const char* value(const ::robot::direction_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::direction_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed\n"
"int32 reverse\n"
"int32 turn\n"
;
  }

  static const char* value(const ::robot::direction_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::direction_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.reverse);
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct direction_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::direction_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::direction_msg_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "reverse: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reverse);
    s << indent << "turn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_DIRECTION_MSG_H
