(cl:defpackage robot-msg
  (:use )
  (:export
   "<DIRECTION_MSG>"
   "DIRECTION_MSG"
   "<ROBOT_ACTIONSACTION>"
   "ROBOT_ACTIONSACTION"
   "<ROBOT_ACTIONSACTIONFEEDBACK>"
   "ROBOT_ACTIONSACTIONFEEDBACK"
   "<ROBOT_ACTIONSACTIONGOAL>"
   "ROBOT_ACTIONSACTIONGOAL"
   "<ROBOT_ACTIONSACTIONRESULT>"
   "ROBOT_ACTIONSACTIONRESULT"
   "<ROBOT_ACTIONSFEEDBACK>"
   "ROBOT_ACTIONSFEEDBACK"
   "<ROBOT_ACTIONSGOAL>"
   "ROBOT_ACTIONSGOAL"
   "<ROBOT_ACTIONSRESULT>"
   "ROBOT_ACTIONSRESULT"
  ))

