; Auto-generated. Do not edit!


(cl:in-package robot-msg)


;//! \htmlinclude robot_actionsResult.msg.html

(cl:defclass <robot_actionsResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass robot_actionsResult (<robot_actionsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_actionsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_actionsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot-msg:<robot_actionsResult> is deprecated: use robot-msg:robot_actionsResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <robot_actionsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:success-val is deprecated.  Use robot-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_actionsResult>) ostream)
  "Serializes a message object of type '<robot_actionsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_actionsResult>) istream)
  "Deserializes a message object of type '<robot_actionsResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_actionsResult>)))
  "Returns string type for a message object of type '<robot_actionsResult>"
  "robot/robot_actionsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_actionsResult)))
  "Returns string type for a message object of type 'robot_actionsResult"
  "robot/robot_actionsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_actionsResult>)))
  "Returns md5sum for a message object of type '<robot_actionsResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_actionsResult)))
  "Returns md5sum for a message object of type 'robot_actionsResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_actionsResult>)))
  "Returns full string definition for message of type '<robot_actionsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_actionsResult)))
  "Returns full string definition for message of type 'robot_actionsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_actionsResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_actionsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_actionsResult
    (cl:cons ':success (success msg))
))
