; Auto-generated. Do not edit!


(cl:in-package robot-msg)


;//! \htmlinclude robot_actionsGoal.msg.html

(cl:defclass <robot_actionsGoal> (roslisp-msg-protocol:ros-message)
  ((longitude
    :reader longitude
    :initarg :longitude
    :type cl:float
    :initform 0.0)
   (latitude
    :reader latitude
    :initarg :latitude
    :type cl:float
    :initform 0.0))
)

(cl:defclass robot_actionsGoal (<robot_actionsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_actionsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_actionsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot-msg:<robot_actionsGoal> is deprecated: use robot-msg:robot_actionsGoal instead.")))

(cl:ensure-generic-function 'longitude-val :lambda-list '(m))
(cl:defmethod longitude-val ((m <robot_actionsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:longitude-val is deprecated.  Use robot-msg:longitude instead.")
  (longitude m))

(cl:ensure-generic-function 'latitude-val :lambda-list '(m))
(cl:defmethod latitude-val ((m <robot_actionsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:latitude-val is deprecated.  Use robot-msg:latitude instead.")
  (latitude m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_actionsGoal>) ostream)
  "Serializes a message object of type '<robot_actionsGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'longitude))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'latitude))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_actionsGoal>) istream)
  "Deserializes a message object of type '<robot_actionsGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'longitude) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'latitude) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_actionsGoal>)))
  "Returns string type for a message object of type '<robot_actionsGoal>"
  "robot/robot_actionsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_actionsGoal)))
  "Returns string type for a message object of type 'robot_actionsGoal"
  "robot/robot_actionsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_actionsGoal>)))
  "Returns md5sum for a message object of type '<robot_actionsGoal>"
  "826f8fcadfa8742a6495798d3978624a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_actionsGoal)))
  "Returns md5sum for a message object of type 'robot_actionsGoal"
  "826f8fcadfa8742a6495798d3978624a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_actionsGoal>)))
  "Returns full string definition for message of type '<robot_actionsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define goals (longitude and latitutude)~%float32 longitude~%float32 latitude~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_actionsGoal)))
  "Returns full string definition for message of type 'robot_actionsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define goals (longitude and latitutude)~%float32 longitude~%float32 latitude~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_actionsGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_actionsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_actionsGoal
    (cl:cons ':longitude (longitude msg))
    (cl:cons ':latitude (latitude msg))
))
