; Auto-generated. Do not edit!


(cl:in-package robot-msg)


;//! \htmlinclude robot_actionsActionGoal.msg.html

(cl:defclass <robot_actionsActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type robot-msg:robot_actionsGoal
    :initform (cl:make-instance 'robot-msg:robot_actionsGoal)))
)

(cl:defclass robot_actionsActionGoal (<robot_actionsActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_actionsActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_actionsActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot-msg:<robot_actionsActionGoal> is deprecated: use robot-msg:robot_actionsActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <robot_actionsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:header-val is deprecated.  Use robot-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <robot_actionsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:goal_id-val is deprecated.  Use robot-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <robot_actionsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot-msg:goal-val is deprecated.  Use robot-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_actionsActionGoal>) ostream)
  "Serializes a message object of type '<robot_actionsActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_actionsActionGoal>) istream)
  "Deserializes a message object of type '<robot_actionsActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_actionsActionGoal>)))
  "Returns string type for a message object of type '<robot_actionsActionGoal>"
  "robot/robot_actionsActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_actionsActionGoal)))
  "Returns string type for a message object of type 'robot_actionsActionGoal"
  "robot/robot_actionsActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_actionsActionGoal>)))
  "Returns md5sum for a message object of type '<robot_actionsActionGoal>"
  "8d404cf946e7659dd367631fed9b8d17")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_actionsActionGoal)))
  "Returns md5sum for a message object of type 'robot_actionsActionGoal"
  "8d404cf946e7659dd367631fed9b8d17")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_actionsActionGoal>)))
  "Returns full string definition for message of type '<robot_actionsActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%robot_actionsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: robot/robot_actionsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define goals (longitude and latitutude)~%float32 longitude~%float32 latitude~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_actionsActionGoal)))
  "Returns full string definition for message of type 'robot_actionsActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%robot_actionsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: robot/robot_actionsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define goals (longitude and latitutude)~%float32 longitude~%float32 latitude~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_actionsActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_actionsActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_actionsActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
