// Auto-generated. Do not edit!

// (in-package robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class robot_actionsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_long = null;
      this.current_lat = null;
    }
    else {
      if (initObj.hasOwnProperty('current_long')) {
        this.current_long = initObj.current_long
      }
      else {
        this.current_long = 0.0;
      }
      if (initObj.hasOwnProperty('current_lat')) {
        this.current_lat = initObj.current_lat
      }
      else {
        this.current_lat = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type robot_actionsFeedback
    // Serialize message field [current_long]
    bufferOffset = _serializer.float32(obj.current_long, buffer, bufferOffset);
    // Serialize message field [current_lat]
    bufferOffset = _serializer.float32(obj.current_lat, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type robot_actionsFeedback
    let len;
    let data = new robot_actionsFeedback(null);
    // Deserialize message field [current_long]
    data.current_long = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [current_lat]
    data.current_lat = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot/robot_actionsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '02a7c0fb9633ae41b2997d7c1088daa1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # define feedback
    float32 current_long
    float32 current_lat
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new robot_actionsFeedback(null);
    if (msg.current_long !== undefined) {
      resolved.current_long = msg.current_long;
    }
    else {
      resolved.current_long = 0.0
    }

    if (msg.current_lat !== undefined) {
      resolved.current_lat = msg.current_lat;
    }
    else {
      resolved.current_lat = 0.0
    }

    return resolved;
    }
};

module.exports = robot_actionsFeedback;
